### ISSUE TITLE
Add status info for each goal

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#44] opened 2019-01-25 18:19 UTC
**Story:** As a user, I want to be able to snooze notifications for goals on a goal-by-goal basis.

**Implementation**: Modify the Goal component to display the status of a goal: 
- [ ] Show days until reminder w/ alarm clock icon
- [ ] Show completion button

The result should look similar to this snapshot (but without the drop-down element, just displaying the current reminder date) but it doesn't need to be functional or fully styled.
<img src="https://user-images.githubusercontent.com/1809882/60131742-1074e500-9768-11e9-9450-57f672e0622c.png" width=300/>

Tapping a goal on the main  screen opens this modal:
![image](https://user-images.githubusercontent.com/37085086/62173166-031cbe80-b303-11e9-8a75-bb1fcf4273dc.png)

**Definition of Done:**
- Each goal should display the selected snooze text
- Tapping the goal on  the main  screen opens the modal for the user to choose a date.

**Comment by kmeyersvt** [comment] 2019-07-30 23:04
Discussion in Hack Night - Nick asked about using  an accordion  pane instead so that  it doesn't resize? Is  this possible?

**Comment by kmeyersvt** [comment] 2019-07-30 23:07
Asked  Siuan if we have a asset for the clock because  it's not in the free version of Font Awesome

**Comment by mpettit** [comment] 2019-08-04 16:22
I believe from discussions at hack night, the essence of this issue has changed as well.  The goal as discussed here will be having just the Goal title, and when tapping a goal, it should open the screen in the second snip above (implementing components in that screen are part of I[ssue 87](https://github.com/codeforbtv/cvoeo-app/issues/87))

**Comment by johnneed** [comment] 2019-09-01 21:42
This is a dupe of #93 and was completed in PR #109 
Closing this issue

**Closed by johnneed** 2019-09-01 21:42 UTC
Labels: UI, blocker, goal details
